export * from "./clientes";
export * from "./pacientes";
export * from "./consultas";
export * from "./recetas";
export * from "./pruebas";
export * from "./movimientos";
export * from "./hospitalizaciones";
export * from "./hospitalizacion_archivos";
export * from "./procedimientos";
